### ISSUE TITLE
Problem with Ruby 2.5?

### ISSUE THREAD

**Issue by obilodeau** [jirutka/asciidoctor-templates-compiler#1]
See https://travis-ci.org/asciidoctor/asciidoctor-reveal.js/jobs/335441645

**Comment by jirutka** [comment]
This is problem in [ruby-beautify](https://github.com/erniebrodeur/ruby-beautify/); it’s already reported in https://github.com/erniebrodeur/ruby-beautify/issues/45. Meanwhile you can disable pretty-formatting by setting `pretty: false`.

**Comment by obilodeau** [comment]
The suggested workaround seems to work! Thanks!

**Comment by jirutka** [comment]
Author of ruby-beautify is not responding to PRs nor email, so I've eventually forked this gem as [ruby-beautify2](https://github.com/jirutka/ruby-beautify2). The latest version of asciidoctor-templates-compiler (0.4.0) depends on the fork, so this issue is fixed now.
